ALTER TABLE branch ADD COLUMN resolved_count INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE branch ADD COLUMN total_issues INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE branch ADD COLUMN medium_severity_count INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE branch ADD COLUMN high_severity_count INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE branch ADD COLUMN low_severity_count INTEGER DEFAULT 0 NOT NULL;