package org.rostilos.codecrow.core.service.qadoc;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** Splits rendered QA markdown into overview, test cases, and environment/setup notes. */
public final class QaDocContentParser {

    public static final String TEST_CASES_START = "<!-- codecrow-test-cases:start -->";
    public static final String TEST_CASES_CONTENT = "<!-- codecrow-test-cases:content -->";
    public static final String TEST_CASES_END = "<!-- codecrow-test-cases:end -->";
    public static final String ENVIRONMENT_START = "<!-- codecrow-environment:start -->";
    public static final String ENVIRONMENT_CONTENT = "<!-- codecrow-environment:content -->";
    public static final String ENVIRONMENT_END = "<!-- codecrow-environment:end -->";

    private static final Pattern SCENARIO_PATTERN = Pattern.compile(
            "(?m)^\\s*\\*\\*(.+?)\\*\\*\\s*\\((HIGH|MEDIUM|LOW)\\)[^\\r\\n]*$",
            Pattern.CASE_INSENSITIVE
    );
    private static final Pattern HEADING_PATTERN = Pattern.compile("(?m)^\\s*(#{2,6})\\s+(.+?)\\s*$");
    private static final Pattern GENERATED_QA_FOOTER = Pattern.compile(
            "(?ms)\\n\\s*---\\s*\\R\\s*\\*🐦 Generated by \\[CodeCrow]\\([^\\r\\n]+\\) "
                    + "QA Auto-Documentation\\*\\s*\\R\\s*"
                    + "<!--\\s*codecrow-qa-autodoc(?::[^>]*)?-->\\s*$"
    );

    private QaDocContentParser() {
    }

    public static QaDocContent parse(String markdown) {
        String source = markdown == null
                ? ""
                : GENERATED_QA_FOOTER.matcher(markdown.trim()).replaceFirst("").trim();
        MarkedBlock testCasesBlock = findMarkedBlock(
                source,
                TEST_CASES_START,
                TEST_CASES_CONTENT,
                TEST_CASES_END);
        MarkedBlock environmentBlock = findMarkedBlock(
                source,
                ENVIRONMENT_START,
                ENVIRONMENT_CONTENT,
                ENVIRONMENT_END);

        List<QaDocTestCase> testCases = testCasesBlock == null
                ? List.of()
                : parseTestCases(testCasesBlock.contentMarkdown());
        String environment = environmentBlock == null
                ? null
                : normalizeNullablePart(environmentBlock.contentMarkdown());

        List<MarkedBlock> excludedBlocks = new ArrayList<>();
        if (testCasesBlock != null) {
            excludedBlocks.add(testCasesBlock);
        }
        if (environmentBlock != null) {
            excludedBlocks.add(environmentBlock);
        }
        excludedBlocks.sort((left, right) -> Integer.compare(left.start(), right.start()));

        return new QaDocContent(
                normalizeDocumentPart(removeBlocks(source, excludedBlocks)),
                testCases,
                environment);
    }

    /**
     * Parses only the exact test-case sentinel block for unauthenticated disclosure.
     * No heading text is inspected or inferred at this authorization boundary.
     */
    public static List<QaDocTestCase> parseMarkedTestCases(String markdown) {
        MarkedBlock block = findMarkedBlock(
                markdown == null ? "" : markdown.trim(),
                TEST_CASES_START,
                TEST_CASES_CONTENT,
                TEST_CASES_END);
        return block == null
                ? List.of()
                : parseStructuredTestCases(block.contentMarkdown());
    }

    /** Returns whether both shareable sections satisfy the exact sentinel contract. */
    public static boolean hasCompleteShareableSections(String markdown) {
        String source = markdown == null ? "" : markdown.trim();
        MarkedBlock testCasesBlock = findMarkedBlock(
                source,
                TEST_CASES_START,
                TEST_CASES_CONTENT,
                TEST_CASES_END);
        MarkedBlock environmentBlock = findMarkedBlock(
                source,
                ENVIRONMENT_START,
                ENVIRONMENT_CONTENT,
                ENVIRONMENT_END);
        return testCasesBlock != null
                && !parseStructuredTestCases(testCasesBlock.contentMarkdown()).isEmpty()
                && environmentBlock != null
                && testCasesBlock.end() <= environmentBlock.start()
                && !environmentBlock.contentMarkdown().isBlank();
    }

    /**
     * Keeps the compact Jira-facing parts of the rendered QA document while replacing
     * each exact shareable block with its opaque localized heading and preview link.
     */
    public static String replaceShareableSections(
            String markdown,
            String testCasesReplacement,
            String environmentReplacement) {
        String source = markdown == null ? "" : markdown.trim();
        String testCasesLink = requireReplacement(testCasesReplacement, "Test-case");
        String environmentLink = requireReplacement(environmentReplacement, "Environment");

        MarkedBlock testCasesBlock = requireMarkedBlock(
                source,
                TEST_CASES_START,
                TEST_CASES_CONTENT,
                TEST_CASES_END,
                "test-case");
        source = replaceBlock(source, testCasesBlock, testCasesLink);

        MarkedBlock environmentBlock = requireMarkedBlock(
                source,
                ENVIRONMENT_START,
                ENVIRONMENT_CONTENT,
                ENVIRONMENT_END,
                "environment/setup");
        return replaceBlock(source, environmentBlock, environmentLink);
    }

    private static String requireReplacement(String replacementMarkdown, String sectionName) {
        String replacement = replacementMarkdown == null ? "" : replacementMarkdown.trim();
        if (replacement.isBlank()) {
            throw new IllegalArgumentException(sectionName + " replacement is required.");
        }
        return replacement;
    }

    private static MarkedBlock requireMarkedBlock(
            String markdown,
            String startMarker,
            String contentMarker,
            String endMarker,
            String sectionName) {
        MarkedBlock block = findMarkedBlock(markdown, startMarker, contentMarker, endMarker);
        if (block == null) {
            throw new IllegalArgumentException(
                    "A complete marked QA " + sectionName + " section is required.");
        }
        return block;
    }

    private static MarkedBlock findMarkedBlock(
            String markdown,
            String startMarker,
            String contentMarker,
            String endMarker) {
        if (countOccurrences(markdown, startMarker) != 1
                || countOccurrences(markdown, contentMarker) != 1
                || countOccurrences(markdown, endMarker) != 1) {
            return null;
        }

        int start = markdown.indexOf(startMarker);
        int contentMarkerStart = markdown.indexOf(contentMarker, start + startMarker.length());
        int endMarkerStart = markdown.indexOf(endMarker, contentMarkerStart + contentMarker.length());
        if (start < 0 || contentMarkerStart < 0 || endMarkerStart < 0) {
            return null;
        }

        String heading = markdown.substring(
                start + startMarker.length(),
                contentMarkerStart).trim();
        String content = markdown.substring(
                contentMarkerStart + contentMarker.length(),
                endMarkerStart).trim();
        if (heading.isBlank()
                || !heading.startsWith("#")
                || heading.contains("\n")
                || content.isBlank()) {
            return null;
        }

        return new MarkedBlock(
                start,
                endMarkerStart + endMarker.length(),
                heading,
                content);
    }

    private static int countOccurrences(String value, String marker) {
        int count = 0;
        int fromIndex = 0;
        while (true) {
            int found = value.indexOf(marker, fromIndex);
            if (found < 0) {
                return count;
            }
            count++;
            fromIndex = found + marker.length();
        }
    }

    private static String replaceBlock(String markdown, MarkedBlock block, String replacement) {
        String prefix = markdown.substring(0, block.start()).stripTrailing();
        String suffix = markdown.substring(block.end()).stripLeading();
        StringBuilder result = new StringBuilder();
        appendDocumentPart(result, prefix);
        appendDocumentPart(result, block.headingMarkdown() + "\n\n" + replacement);
        appendDocumentPart(result, suffix);
        return result.toString();
    }

    private static String removeBlocks(String markdown, List<MarkedBlock> blocks) {
        StringBuilder result = new StringBuilder();
        int cursor = 0;
        for (MarkedBlock block : blocks) {
            if (block.start() < cursor) {
                cursor = Math.max(cursor, block.end());
                continue;
            }
            appendDocumentPart(result, markdown.substring(cursor, block.start()));
            cursor = block.end();
        }
        appendDocumentPart(result, markdown.substring(cursor));
        return result.toString();
    }

    private static void appendDocumentPart(StringBuilder target, String value) {
        String part = value == null ? "" : value.trim();
        if (part.isBlank()) {
            return;
        }
        if (!target.isEmpty()) {
            target.append("\n\n");
        }
        target.append(part);
    }

    private static String normalizeDocumentPart(String value) {
        return value == null
                ? ""
                : value.trim().replaceAll("\\n{3,}", "\n\n");
    }

    private static String normalizeNullablePart(String value) {
        String normalized = normalizeDocumentPart(value);
        return normalized.isBlank() ? null : normalized;
    }

    private static List<QaDocTestCase> parseTestCases(String section) {
        List<QaDocTestCase> structured = parseStructuredTestCases(section);
        if (!structured.isEmpty()) {
            return structured;
        }
        String fallback = normalizeDocumentPart(section);
        return fallback.isBlank()
                ? List.of()
                : List.of(new QaDocTestCase("Test scenarios", null, null, fallback));
    }

    private static List<QaDocTestCase> parseStructuredTestCases(String section) {
        Matcher matcher = SCENARIO_PATTERN.matcher(section);
        List<ScenarioMatch> matches = new ArrayList<>();
        while (matcher.find()) {
            matches.add(new ScenarioMatch(
                    matcher.start(),
                    matcher.end(),
                    matcher.group(1).trim(),
                    matcher.group(2).toUpperCase(Locale.ROOT)
            ));
        }

        if (matches.isEmpty()) {
            return List.of();
        }

        List<QaDocTestCase> testCases = new ArrayList<>();
        for (int index = 0; index < matches.size(); index++) {
            ScenarioMatch current = matches.get(index);
            int descriptionEnd = index + 1 < matches.size()
                    ? matches.get(index + 1).start()
                    : section.length();

            Matcher interveningHeading = HEADING_PATTERN.matcher(section);
            interveningHeading.region(current.end(), descriptionEnd);
            if (interveningHeading.find()) {
                descriptionEnd = interveningHeading.start();
            }

            String description = section.substring(current.end(), descriptionEnd).trim();
            testCases.add(new QaDocTestCase(
                    current.title(),
                    current.priority(),
                    findFunctionalArea(section, current.start()),
                    description
            ));
        }
        return List.copyOf(testCases);
    }

    private static String findFunctionalArea(String section, int beforePosition) {
        Matcher headings = HEADING_PATTERN.matcher(section);
        String latest = null;
        while (headings.find() && headings.start() < beforePosition) {
            latest = headings.group(2).trim();
        }
        return latest;
    }

    private record MarkedBlock(
            int start,
            int end,
            String headingMarkdown,
            String contentMarkdown
    ) {
    }

    private record ScenarioMatch(int start, int end, String title, String priority) {
    }
}
