"""Lightweight Stage 1 repository-tool inventory."""

STAGE1_REVIEW_FILE_TOOL_NAME = "getReviewFileContent"
STAGE1_BRANCH_FILE_TOOL_NAME = "getBranchFileContent"
STAGE1_VCS_TOOL_NAMES = frozenset({
    STAGE1_REVIEW_FILE_TOOL_NAME,
    STAGE1_BRANCH_FILE_TOOL_NAME,
})
STAGE1_LEGACY_VCS_TOOL_NAMES = frozenset({STAGE1_BRANCH_FILE_TOOL_NAME})
STAGE1_REVIEW_CONTEXT_TOOL_NAME = "exploreReviewContext"
STAGE1_MINIMAL_REVIEW_CONTEXT_TOOL_NAME = "getMinimalReviewContext"
STAGE1_IMPACT_RADIUS_TOOL_NAME = "getImpactRadius"
STAGE1_TRAVERSE_GRAPH_TOOL_NAME = "traverseCodeGraph"
STAGE1_QUERY_GRAPH_TOOL_NAME = "queryCodeGraph"
STAGE1_STRUCTURAL_UNIT_TOOL_NAME = "getStructuralUnit"
STAGE1_REQUIRED_STRUCTURAL_TOOL_SEQUENCE = (
    STAGE1_MINIMAL_REVIEW_CONTEXT_TOOL_NAME,
    STAGE1_IMPACT_RADIUS_TOOL_NAME,
    STAGE1_QUERY_GRAPH_TOOL_NAME,
    STAGE1_STRUCTURAL_UNIT_TOOL_NAME,
)
STAGE1_STRUCTURAL_TOOL_NAMES = frozenset({
    STAGE1_REVIEW_CONTEXT_TOOL_NAME,
    STAGE1_MINIMAL_REVIEW_CONTEXT_TOOL_NAME,
    STAGE1_IMPACT_RADIUS_TOOL_NAME,
    STAGE1_TRAVERSE_GRAPH_TOOL_NAME,
    STAGE1_QUERY_GRAPH_TOOL_NAME,
    STAGE1_STRUCTURAL_UNIT_TOOL_NAME,
})
STAGE1_STRUCTURAL_OBSERVATION_TOOL_NAMES = frozenset({
    STAGE1_REVIEW_CONTEXT_TOOL_NAME,
    *STAGE1_STRUCTURAL_TOOL_NAMES,
})
# The target-head relation endpoint remains available for compatible internal
# callers. Stage 1 model tools are proposed-tree operations bound to the sealed
# review generation; target-head relations are not mixed into review evidence.
STAGE1_NARROW_STRUCTURAL_TOOL_NAMES = frozenset({
    "getStructuralRelations",
})
STAGE1_AGENT_TOOL_NAMES = (
    STAGE1_VCS_TOOL_NAMES | STAGE1_STRUCTURAL_TOOL_NAMES
)
