package org.rostilos.codecrow.webserver;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.MigrationVersion;
import org.flywaydb.core.api.output.MigrateResult;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

import javax.sql.DataSource;
import java.util.List;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Owner-side proof that the managed migration chain advances an existing 2.14
 * installation through the manifest, coverage, distinct-execution, and durable
 * delivery migrations. The application IT profile keeps automatic Flyway
 * disabled, so this test owns both explicit migrate calls and its isolated
 * schema lifecycle.
 */
class ManagedImmutableManifestFlywayIT extends BaseWebServerIT {

    private static final String SCHEMA = "p101_managed_manifest";
    private static final String QUALIFIED_HISTORY =
            SCHEMA + ".flyway_schema_history";
    private static final String LEGACY_SHA = "a".repeat(40);
    private static final String BASE_SHA = "b".repeat(40);
    private static final String HEAD_SHA = "c".repeat(40);
    private static final String MERGE_BASE_SHA = "d".repeat(40);
    private static final String EXECUTION_ID = "execution:p101-managed-it";
    private static final String DIFF_ARTIFACT_ID = "diff:p101-managed-it";
    private static final String MANIFEST_DIGEST = "e".repeat(64);
    private static final String DIFF_DIGEST =
            "ff502a8ddd511153800932bb47b1b9f0e74c81b85f8fbbd600c32f727dbf7917";
    private static final byte[] DIFF_BYTES =
            "+bound-line\n".getBytes(java.nio.charset.StandardCharsets.UTF_8);

    @Autowired
    private DataSource dataSource;

    private JdbcTemplate jdbc;
    private TransactionTemplate transaction;

    @BeforeEach
    void createIsolatedManagedSchema() {
        jdbc = new JdbcTemplate(dataSource);
        transaction = new TransactionTemplate(new DataSourceTransactionManager(dataSource));
        jdbc.execute("DROP SCHEMA IF EXISTS " + SCHEMA + " CASCADE");
        jdbc.execute("CREATE SCHEMA " + SCHEMA);
        jdbc.execute("CREATE TABLE " + SCHEMA + ".workspace (id BIGINT PRIMARY KEY)");
        jdbc.execute("CREATE TABLE " + SCHEMA + ".project (id BIGINT PRIMARY KEY)");
        for (String table : List.of(
                "job",
                "analysis_lock",
                "pull_request",
                "analyzed_file_snapshot",
                "analyzed_commit")) {
            jdbc.execute("CREATE TABLE " + SCHEMA + "." + table
                    + " (id BIGINT PRIMARY KEY, commit_hash VARCHAR(40))");
        }
        jdbc.execute("""
                CREATE TABLE %s.code_analysis (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    project_id BIGINT NOT NULL,
                    pr_number BIGINT,
                    commit_hash VARCHAR(40),
                    CONSTRAINT uq_code_analysis_project_commit
                        UNIQUE (project_id, commit_hash)
                )
                """.formatted(SCHEMA));
        jdbc.execute("""
                CREATE TABLE %s.code_analysis_issue (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    resolved_commit_hash VARCHAR(40)
                )
                """.formatted(SCHEMA));
    }

    @AfterEach
    void dropIsolatedManagedSchema() {
        if (jdbc != null) {
            jdbc.execute("DROP SCHEMA IF EXISTS " + SCHEMA + " CASCADE");
        }
    }

    @Test
    void webServerOwnerMigratesManaged214Through218AndRepeatMigrateIsIdempotent() {
        MigrateResult to214 = managedFlyway("2.14.0").migrate();

        assertThat(to214.migrationsExecuted).isEqualTo(1);
        assertThat(successfulVersions())
                .hasSize(2)
                .contains("2.14.0")
                .doesNotContain("2.15.0");
        assertThat(columnNames("workspace")).contains("analysis_limits");
        assertThat(tableNames()).doesNotContain("review_execution", "review_artifact");
        seedLegacy214Rows();

        Flyway owner = managedFlyway("2.18.0");
        MigrateResult to218 = owner.migrate();

        assertThat(to218.migrationsExecuted).isEqualTo(4);
        assertThat(successfulVersions())
                .hasSize(6)
                .contains(
                        "2.14.0",
                        "2.15.0",
                        "2.16.0",
                        "2.17.0",
                        "2.18.0");
        assertManaged218Objects();
        assertLegacyRowsSurvived();

        int historyRows = successfulVersions().size();
        MigrateResult repeated = owner.migrate();

        assertThat(repeated.migrationsExecuted).isZero();
        assertThat(successfulVersions()).hasSize(historyRows);
        assertManaged218Objects();
        assertLegacyRowsSurvived();
        assertManagedManifestEnforcement();
        assertDistinctCandidateExecutionsAtSameHead();
    }

    private Flyway managedFlyway(String target) {
        return Flyway.configure(getClass().getClassLoader())
                .dataSource(dataSource)
                .schemas(SCHEMA)
                .defaultSchema(SCHEMA)
                .locations("classpath:db/migration/managed")
                .baselineOnMigrate(true)
                .baselineVersion(MigrationVersion.fromVersion("2.13.0"))
                .target(MigrationVersion.fromVersion(target))
                .cleanDisabled(true)
                .load();
    }

    private void assertManaged218Objects() {
        assertThat(tableNames()).contains(
                "review_execution",
                "review_artifact",
                "review_coverage_anchor",
                "review_coverage_disposition",
                "review_analysis_state",
                "review_delivery_current_head",
                "review_delivery_outbox");
        assertThat(columnNames("review_execution")).contains(
                "id",
                "project_id",
                "pull_request_id",
                "base_sha",
                "head_sha",
                "diff_artifact_id",
                "artifact_manifest_digest");
        assertThat(columnNames("review_artifact")).contains(
                "id",
                "execution_id",
                "artifact_manifest_digest",
                "content_key",
                "snapshot_sha",
                "content_digest",
                "byte_length",
                "content_bytes");
        assertThat(columnNames("review_coverage_anchor")).contains(
                "anchor_id",
                "execution_id",
                "artifact_manifest_digest",
                "ledger_digest",
                "initial_state");
        assertThat(columnNames("review_coverage_disposition")).contains(
                "execution_id",
                "anchor_id",
                "coverage_state",
                "reason_code");
        assertThat(columnNames("review_analysis_state")).contains(
                "execution_id",
                "analysis_state",
                "inventory_anchor_count",
                "reason_counts",
                "revision");
        assertThat(columnNames("review_delivery_current_head")).contains(
                "provider",
                "project_id",
                "pull_request_id",
                "head_generation",
                "execution_id",
                "artifact_manifest_digest",
                "head_sha");
        assertThat(columnNames("review_delivery_outbox")).contains(
                "intent_id",
                "execution_id",
                "code_analysis_id",
                "head_generation",
                "idempotency_key",
                "state",
                "next_attempt_at");
        assertThat(columnNames("code_analysis")).contains(
                "execution_id", "artifact_manifest_digest");
        assertThat(characterMaximumLength("code_analysis", "commit_hash"))
                .isEqualTo(64);
        assertThat(characterMaximumLength(
                "code_analysis_issue", "resolved_commit_hash"))
                .isEqualTo(64);
        for (String table : List.of(
                "job",
                "analysis_lock",
                "pull_request",
                "analyzed_file_snapshot",
                "analyzed_commit")) {
            assertThat(characterMaximumLength(table, "commit_hash"))
                    .as(table + ".commit_hash")
                    .isEqualTo(64);
        }
        assertThat(dataType("review_artifact", "content_bytes")).isEqualTo("bytea");

        assertThat(constraintNames()).contains(
                "uq_review_execution_analysis_binding",
                "fk_review_execution_initial_diff",
                "fk_review_artifact_manifest_owner",
                "uq_review_artifact_content_key",
                "ck_review_artifact_content_length",
                "uq_code_analysis_execution_id",
                "fk_code_analysis_execution_binding",
                "ck_code_analysis_execution_binding_pair",
                "fk_review_coverage_anchor_manifest",
                "fk_review_coverage_disposition_anchor",
                "fk_review_analysis_state_manifest",
                "pk_review_delivery_current_head",
                "fk_review_delivery_current_head_execution",
                "fk_review_delivery_manifest",
                "fk_review_delivery_analysis",
                "uq_review_delivery_idempotency_key",
                "uq_review_delivery_intent");
        assertThat(constraintNames()).doesNotContain(
                "uq_code_analysis_project_commit");
        assertThat(triggerNames()).contains(
                "review_execution_immutable_update",
                "review_artifact_immutable_update",
                "code_analysis_execution_identity_immutable_update",
                "review_coverage_anchor_immutable_update",
                "review_coverage_disposition_identity_update",
                "review_analysis_state_identity_update",
                "trg_review_delivery_current_head_monotonic",
                "trg_review_delivery_updated_at");
    }

    private void seedLegacy214Rows() {
        jdbc.update("INSERT INTO " + SCHEMA + ".workspace (id) VALUES (1)");
        jdbc.update("INSERT INTO " + SCHEMA + ".project (id) VALUES (1)");
        long id = 10;
        for (String table : List.of(
                "job",
                "analysis_lock",
                "pull_request",
                "analyzed_file_snapshot",
                "analyzed_commit")) {
            jdbc.update(
                    "INSERT INTO " + SCHEMA + "." + table
                            + " (id, commit_hash) VALUES (?, ?)",
                    id++,
                    LEGACY_SHA);
        }
        jdbc.update("""
                INSERT INTO %s.code_analysis (project_id, pr_number, commit_hash)
                VALUES (1, 17, ?)
                """.formatted(SCHEMA), LEGACY_SHA);
        jdbc.update("""
                INSERT INTO %s.code_analysis_issue (resolved_commit_hash)
                VALUES (?)
                """.formatted(SCHEMA), LEGACY_SHA);
    }

    private void assertLegacyRowsSurvived() {
        for (String table : List.of(
                "job",
                "analysis_lock",
                "pull_request",
                "analyzed_file_snapshot",
                "analyzed_commit")) {
            assertThat(jdbc.queryForObject(
                    "SELECT commit_hash FROM " + SCHEMA + "." + table,
                    String.class))
                    .as(table + " legacy commit")
                    .isEqualTo(LEGACY_SHA);
        }
        assertThat(jdbc.queryForObject(
                "SELECT commit_hash FROM " + SCHEMA + ".code_analysis",
                String.class)).isEqualTo(LEGACY_SHA);
        assertThat(jdbc.queryForObject(
                "SELECT resolved_commit_hash FROM " + SCHEMA + ".code_analysis_issue",
                String.class)).isEqualTo(LEGACY_SHA);
        assertThat(jdbc.queryForObject(
                "SELECT execution_id IS NULL AND artifact_manifest_digest IS NULL "
                        + "FROM " + SCHEMA + ".code_analysis",
                Boolean.class)).isTrue();
    }

    private void assertManagedManifestEnforcement() {
        transaction.execute(status -> {
            insertExecution(EXECUTION_ID, DIFF_ARTIFACT_ID, MANIFEST_DIGEST);
            insertArtifact(
                    DIFF_ARTIFACT_ID,
                    EXECUTION_ID,
                    MANIFEST_DIGEST,
                    "raw-diff",
                    "pull-request.diff",
                    DIFF_BYTES.length,
                    DIFF_BYTES);
            return null;
        });

        assertConstraintRejected(
                () -> transaction.execute(status -> {
                    insertExecution(
                            "execution:p101-missing-diff",
                            "diff:p101-missing",
                            "f".repeat(64));
                    return null;
                }),
                "fk_review_execution_initial_diff");
        assertConstraintRejected(
                () -> insertArtifact(
                        "source:p101-wrong-owner",
                        EXECUTION_ID,
                        "f".repeat(64),
                        "source-file",
                        "src/WrongOwner.java",
                        1,
                        new byte[]{1}),
                "fk_review_artifact_manifest_owner");
        assertConstraintRejected(
                () -> insertArtifact(
                        "source:p101-wrong-length",
                        EXECUTION_ID,
                        MANIFEST_DIGEST,
                        "source-file",
                        "src/WrongLength.java",
                        2,
                        new byte[]{1}),
                "ck_review_artifact_content_length");

        jdbc.update("""
                INSERT INTO %s.code_analysis (
                    project_id, pr_number, commit_hash,
                    execution_id, artifact_manifest_digest
                ) VALUES (1, 42, ?, ?, ?)
                """.formatted(SCHEMA), HEAD_SHA, EXECUTION_ID, MANIFEST_DIGEST);
        assertConstraintRejected(
                () -> jdbc.update("""
                        INSERT INTO %s.code_analysis (
                            project_id, pr_number, commit_hash,
                            execution_id, artifact_manifest_digest
                        ) VALUES (1, 42, ?, ?, ?)
                        """.formatted(SCHEMA),
                        BASE_SHA,
                        "execution:p101-unknown-binding",
                        MANIFEST_DIGEST),
                "fk_code_analysis_execution_binding");
        assertConstraintRejected(
                () -> jdbc.update("""
                        INSERT INTO %s.code_analysis (
                            project_id, pr_number, commit_hash, execution_id
                        ) VALUES (1, 42, ?, ?)
                        """.formatted(SCHEMA), HEAD_SHA, "execution:p101-partial"),
                "ck_code_analysis_execution_binding_pair");

        assertThatThrownBy(() -> jdbc.update(
                "UPDATE " + SCHEMA
                        + ".review_execution SET policy_version = 'changed-v1' WHERE id = ?",
                EXECUTION_ID))
                .hasStackTraceContaining("immutable review manifest row");
        assertThatThrownBy(() -> jdbc.update(
                "UPDATE " + SCHEMA
                        + ".review_artifact SET content_key = 'changed' WHERE id = ?",
                DIFF_ARTIFACT_ID))
                .hasStackTraceContaining("immutable review manifest row");
        assertThatThrownBy(() -> jdbc.update(
                "UPDATE " + SCHEMA
                        + ".code_analysis SET execution_id = 'execution:p101-changed' "
                        + "WHERE execution_id = ?",
                EXECUTION_ID))
                .hasStackTraceContaining("immutable candidate execution identity");
    }

    private void assertDistinctCandidateExecutionsAtSameHead() {
        String secondExecutionId = "execution:p101-managed-it-second";
        String secondDiffArtifactId = "diff:p101-managed-it-second";
        String secondManifestDigest = "1".repeat(64);

        transaction.execute(status -> {
            insertExecution(
                    secondExecutionId,
                    secondDiffArtifactId,
                    secondManifestDigest);
            insertArtifact(
                    secondDiffArtifactId,
                    secondExecutionId,
                    secondManifestDigest,
                    "raw-diff",
                    "pull-request.diff",
                    DIFF_BYTES.length,
                    DIFF_BYTES);
            return null;
        });
        jdbc.update("""
                INSERT INTO %s.code_analysis (
                    project_id, pr_number, commit_hash,
                    execution_id, artifact_manifest_digest
                ) VALUES (1, 42, ?, ?, ?)
                """.formatted(SCHEMA),
                HEAD_SHA,
                secondExecutionId,
                secondManifestDigest);

        assertThat(jdbc.queryForObject("""
                SELECT COUNT(*)
                FROM %s.code_analysis
                WHERE project_id = 1
                  AND commit_hash = ?
                  AND execution_id IS NOT NULL
                """.formatted(SCHEMA), Integer.class, HEAD_SHA)).isEqualTo(2);
    }

    private void insertExecution(
            String executionId,
            String diffArtifactId,
            String manifestDigest) {
        jdbc.update("""
                INSERT INTO %s.review_execution (
                    id, schema_version, project_id, repository_id, pull_request_id,
                    base_sha, head_sha, merge_base_sha, diff_artifact_id, diff_digest,
                    diff_byte_length, diff_artifact_kind, diff_artifact_producer,
                    diff_artifact_producer_version, artifact_schema_version,
                    policy_version, creation_fence, created_at, artifact_manifest_digest
                ) VALUES (
                    ?, 1, 1, 'github:workspace/repository', 42,
                    ?, ?, ?, ?, ?,
                    ?, 'raw-diff', 'analysis-engine',
                    'analysis-engine-v1', 'review-artifact-v1',
                    'candidate-review-v1', 'fence:p101-managed-it',
                    TIMESTAMPTZ '2026-07-15 00:00:00+00', ?
                )
                """.formatted(SCHEMA),
                executionId,
                BASE_SHA,
                HEAD_SHA,
                MERGE_BASE_SHA,
                diffArtifactId,
                DIFF_DIGEST,
                DIFF_BYTES.length,
                manifestDigest);
    }

    private void insertArtifact(
            String artifactId,
            String executionId,
            String manifestDigest,
            String kind,
            String contentKey,
            long byteLength,
            byte[] content) {
        jdbc.update("""
                INSERT INTO %s.review_artifact (
                    id, execution_id, artifact_manifest_digest, kind, content_key,
                    snapshot_sha, content_digest, byte_length, content_bytes,
                    artifact_schema_version, producer, producer_version
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?,
                          'review-artifact-v1', 'analysis-engine', 'analysis-engine-v1')
                """.formatted(SCHEMA),
                artifactId,
                executionId,
                manifestDigest,
                kind,
                contentKey,
                HEAD_SHA,
                DIFF_DIGEST,
                byteLength,
                content);
    }

    private void assertConstraintRejected(Runnable operation, String constraint) {
        assertThatThrownBy(operation::run).hasStackTraceContaining(constraint);
    }

    private List<String> successfulVersions() {
        return jdbc.queryForList(
                "SELECT version FROM " + QUALIFIED_HISTORY
                        + " WHERE success ORDER BY installed_rank",
                String.class);
    }

    private Set<String> tableNames() {
        return Set.copyOf(jdbc.queryForList("""
                SELECT table_name
                FROM information_schema.tables
                WHERE table_schema = ?
                """, String.class, SCHEMA));
    }

    private Set<String> columnNames(String table) {
        return Set.copyOf(jdbc.queryForList("""
                SELECT column_name
                FROM information_schema.columns
                WHERE table_schema = ? AND table_name = ?
                """, String.class, SCHEMA, table));
    }

    private Integer characterMaximumLength(String table, String column) {
        return jdbc.queryForObject("""
                SELECT character_maximum_length
                FROM information_schema.columns
                WHERE table_schema = ? AND table_name = ? AND column_name = ?
                """, Integer.class, SCHEMA, table, column);
    }

    private String dataType(String table, String column) {
        return jdbc.queryForObject("""
                SELECT data_type
                FROM information_schema.columns
                WHERE table_schema = ? AND table_name = ? AND column_name = ?
                """, String.class, SCHEMA, table, column);
    }

    private Set<String> constraintNames() {
        return Set.copyOf(jdbc.queryForList("""
                SELECT constraint_name
                FROM information_schema.table_constraints
                WHERE constraint_schema = ?
                """, String.class, SCHEMA));
    }

    private Set<String> triggerNames() {
        return Set.copyOf(jdbc.queryForList("""
                SELECT trigger_name
                FROM information_schema.triggers
                WHERE trigger_schema = ?
                """, String.class, SCHEMA));
    }
}
