-- Keep the persisted lifecycle contract aligned with AnalysisStatus. Hibernate's
-- ddl-auto=update does not replace the CHECK generated by an older enum.
-- A review with unavailable evidence still has a valid, persistable PARTIAL
-- result; neither its findings nor its limitations should be lost.
-- Fresh databases may run migrations before Hibernate creates the table; the
-- current entity enum will create an already-compatible constraint in that case.
ALTER TABLE IF EXISTS code_analysis DROP CONSTRAINT IF EXISTS code_analysis_status_check;

ALTER TABLE IF EXISTS code_analysis ADD CONSTRAINT code_analysis_status_check CHECK (
    status IN ('ACCEPTED', 'PARTIAL', 'REJECTED', 'PENDING', 'ERROR')
);
