package org.rostilos.codecrow.pipelineagent.qadoc;

import org.junit.jupiter.api.Test;
import org.rostilos.codecrow.core.dto.admin.BaseUrlSettingsDTO;
import org.rostilos.codecrow.core.model.qadoc.QaDocDocument;
import org.rostilos.codecrow.core.service.SiteSettingsProvider;
import org.rostilos.codecrow.core.service.qadoc.QaDocPublicShareResource;
import org.rostilos.codecrow.publicshare.api.IssuedPublicShare;
import org.rostilos.codecrow.publicshare.service.PublicShareLinkService;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

class QaDocPublicPreviewServiceTest {

    @Test
    void createsAnOpaquePublicLinkAndRedactsShareableBodiesFromTheTaskComment() {
        PublicShareLinkService publicShares = mock(PublicShareLinkService.class);
        SiteSettingsProvider settings = mock(SiteSettingsProvider.class);
        when(publicShares.issue(QaDocPublicShareResource.DOCUMENT, "88"))
                .thenReturn(new IssuedPublicShare("ccs_opaque-public-credential"));
        when(settings.getBaseUrlSettings())
                .thenReturn(new BaseUrlSettingsDTO(
                        "https://api.codecrow.example",
                        "https://app.codecrow.example/",
                        "https://hooks.codecrow.example"
                ));
        QaDocPublicPreviewService service = new QaDocPublicPreviewService(publicShares, settings);
        QaDocDocument document = new QaDocDocument(null, 17L);
        document.setId(88L);
        document.setMarkdownContent("""
                ### 1. Change Summary
                PRESERVED OVERVIEW CONTENT

                ### 2. Scope
                PRESERVED SCOPE CONTENT

                <!-- codecrow-test-cases:start -->
                ### 3. Test Scenarios
                **A shared scenario** (HIGH)
                - **Expected Result:** REDACTED TEST DETAILS

                ### 4. Edge Cases
                PRESERVED EDGE CASE CONTENT

                ### 5. Regression Risks
                PRESERVED REGRESSION RISK CONTENT

                ### 6. Environment and Setup Notes
                PRESERVED SETUP CONTENT
                <!-- codecrow-test-cases:end -->

                ---
                *🐦 Generated by [CodeCrow](https://codecrow.app) QA Auto-Documentation*
                <!-- codecrow-qa-autodoc:prs=17 -->
                """);

        String previewUrl = service.createPreviewUrl(document);
        String comment = service.buildTaskComment(document.getMarkdownContent(), previewUrl);

        assertThat(previewUrl)
                .isEqualTo("https://app.codecrow.example/share#token=ccs_opaque-public-credential");
        assertThat(comment)
                .contains(QaAutoDocListener.COMMENT_MARKER)
                .contains("### 1. Change Summary", "PRESERVED OVERVIEW CONTENT")
                .contains("### 2. Scope", "PRESERVED SCOPE CONTENT")
                .contains("### 3. Test Scenarios\n\n" + previewUrl + "&tab=test-cases")
                .contains("### 4. Edge Cases", "PRESERVED EDGE CASE CONTENT")
                .contains("### 5. Regression Risks", "PRESERVED REGRESSION RISK CONTENT")
                .contains(
                        "### 6. Environment and Setup Notes\n\n"
                                + previewUrl + "&tab=environment",
                        "Generated by [CodeCrow]",
                        "<!-- codecrow-qa-autodoc:prs=17 -->")
                .doesNotContain(
                        "A shared scenario",
                        "REDACTED TEST DETAILS",
                        "PRESERVED SETUP CONTENT")
                .doesNotContain("[View QA test cases in CodeCrow]");
        verify(publicShares).issue(QaDocPublicShareResource.DOCUMENT, "88");
    }

    @Test
    void refusesToIssueALinkForAnUnmarkedDocument() {
        PublicShareLinkService publicShares = mock(PublicShareLinkService.class);
        SiteSettingsProvider settings = mock(SiteSettingsProvider.class);
        QaDocPublicPreviewService service = new QaDocPublicPreviewService(publicShares, settings);
        QaDocDocument document = new QaDocDocument(null, 17L);
        document.setId(88L);
        document.setMarkdownContent("SECRET OVERVIEW CONTENT");

        org.assertj.core.api.Assertions.assertThatThrownBy(
                        () -> service.createPreviewUrl(document))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("marked QA test-case section");
    }
}
