-- Adds tables to track files (per project) and branch-scoped issue mapping
-- 1) project_file - stores known files and their last known issue count
-- 2) project_branch - stores branches with last seen commit for a project
-- 3) branch_code_analysis_issue - mapping of code_analysis_issue -> branch with resolved flag

CREATE TABLE project_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    issue_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT uq_project_file_project_path UNIQUE (project_id, file_path)
);

ALTER TABLE project_file
    ADD CONSTRAINT fk_project_file_project
    FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE;

CREATE INDEX idx_project_file_project_id ON project_file(project_id);
CREATE INDEX idx_project_file_file_path ON project_file(file_path);

CREATE TABLE project_branch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    branch_name VARCHAR(200) NOT NULL,
    commit_hash VARCHAR(40),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT uq_project_branch_project_branch UNIQUE (project_id, branch_name)
);

ALTER TABLE project_branch
    ADD CONSTRAINT fk_project_branch_project
    FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE;

CREATE INDEX idx_project_branch_project_id ON project_branch(project_id);
CREATE INDEX idx_project_branch_commit_hash ON project_branch(commit_hash);

CREATE TABLE branch_code_analysis_issue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL,
    code_analysis_issue_id BIGINT NOT NULL,
    is_resolved BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT uq_branch_issue UNIQUE (branch_id, code_analysis_issue_id)
);

ALTER TABLE branch_code_analysis_issue
    ADD CONSTRAINT fk_branch_issue_branch
    FOREIGN KEY (branch_id) REFERENCES project_branch(id) ON DELETE CASCADE;

ALTER TABLE branch_code_analysis_issue
    ADD CONSTRAINT fk_branch_issue_code_analysis_issue
    FOREIGN KEY (code_analysis_issue_id) REFERENCES code_analysis_issue(id) ON DELETE CASCADE;

CREATE INDEX idx_branch_code_analysis_issue_branch_id ON branch_code_analysis_issue(branch_id);
CREATE INDEX idx_branch_code_analysis_issue_code_analysis_issue_id ON branch_code_analysis_issue(code_analysis_issue_id);

-- Triggers or application-level updates expected to refresh updated_at timestamps.
