package org.rostilos.codecrow.core.service.qadoc;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class QaDocContentParserTest {

    @Test
    void separatesExactSentinelBlocksWithoutInterpretingLocalizedHeadings() {
        String markdown = """
                # QA Guide

                ## Що змінилося
                Змінився процес оформлення.

                <!-- codecrow-test-cases:start -->
                ## 3. Будь-яка локалізована назва
                <!-- codecrow-test-cases:content -->
                ### Оформлення
                **Успішне оформлення** (HIGH)
                - **Передумови:** Товар у кошику
                - **Кроки:**
                  1. Підтвердити замовлення
                - **Очікуваний результат:** Замовлення створено
                <!-- codecrow-test-cases:end -->

                ## 4. Граничні випадки
                Перевірити порожній кошик.

                ## 5. Регресійні ризики
                Перевірити збережений кошик.

                <!-- codecrow-environment:start -->
                ## 6. Довільна назва підготовки
                <!-- codecrow-environment:content -->
                - Використати тестовий платіжний профіль.
                <!-- codecrow-environment:end -->
                """;

        QaDocContent result = QaDocContentParser.parse(markdown);

        assertThat(result.overviewMarkdown())
                .contains("Що змінилося", "Граничні випадки", "Регресійні ризики")
                .doesNotContain(
                        "Будь-яка локалізована назва",
                        "Успішне оформлення",
                        "Довільна назва підготовки",
                        "платіжний профіль",
                        "codecrow-");
        assertThat(result.testCases()).singleElement()
                .extracting(QaDocTestCase::title, QaDocTestCase::priority, QaDocTestCase::functionalArea)
                .containsExactly("Успішне оформлення", "HIGH", "Оформлення");
        assertThat(result.environmentMarkdown())
                .isEqualTo("- Використати тестовий платіжний профіль.");
    }

    @Test
    void doesNotInferShareableSectionsFromHeadingText() {
        QaDocContent result = QaDocContentParser.parse("""
                ## 3. Test Scenarios
                **Open settings** (LOW)
                - **Expected Result:** Settings appear

                ## 6. Environment and Setup Notes
                Use staging.
                """);

        assertThat(result.testCases()).isEmpty();
        assertThat(result.environmentMarkdown()).isNull();
        assertThat(result.overviewMarkdown())
                .contains("Test Scenarios", "Open settings", "Environment and Setup Notes", "Use staging");
    }

    @Test
    void publicParsingRequiresEveryExactTestCaseSentinelAndAStructuredScenario() {
        assertThat(QaDocContentParser.parseMarkedTestCases("""
                <!-- codecrow-test-cases:start -->
                ### Test Scenarios
                **Missing content sentinel** (HIGH)
                <!-- codecrow-test-cases:end -->
                """)).isEmpty();
        assertThat(QaDocContentParser.parseMarkedTestCases("""
                <!-- codecrow-test-cases:start -->
                ### Test Scenarios
                <!-- codecrow-test-cases:content -->
                General notes without a structured scenario.
                <!-- codecrow-test-cases:end -->
                """)).isEmpty();
        assertThat(QaDocContentParser.parseMarkedTestCases("""
                **Unmarked scenario** (HIGH)
                - **Expected Result:** It works
                """)).isEmpty();
    }

    @Test
    void replacesOnlyExactBlocksWithLinksAndPreservesAllOtherSectionsAndFooter() {
        String markdown = """
                ### 1. Change Summary
                Checkout now supports gift cards.

                ### 2. Scope
                Web checkout only.

                <!-- codecrow-test-cases:start -->
                ### 3. Тестові сценарії
                <!-- codecrow-test-cases:content -->
                ### Оформлення
                **Оплатити подарунковою карткою** (HIGH)
                - **Expected Result:** Баланс застосовано.
                <!-- codecrow-test-cases:end -->

                ### 4. Edge Cases and Negative Testing
                Test an expired gift card.

                ### 5. Regression Risks
                Verify saved cards.

                <!-- codecrow-environment:start -->
                ### 6. Налаштування середовища
                <!-- codecrow-environment:content -->
                Use the QA payment environment.
                <!-- codecrow-environment:end -->

                ---
                *🐦 Generated by [CodeCrow](https://codecrow.app) QA Auto-Documentation*
                <!-- codecrow-qa-autodoc:prs=17 -->
                """;

        String result = QaDocContentParser.replaceShareableSections(
                markdown,
                "https://codecrow.cloud/share#token=ccs_public-token&tab=test-cases",
                "https://codecrow.cloud/share#token=ccs_public-token&tab=environment");

        assertThat(result)
                .contains("### 1. Change Summary", "Checkout now supports gift cards")
                .contains("### 2. Scope", "Web checkout only")
                .contains("### 3. Тестові сценарії\n\n"
                        + "https://codecrow.cloud/share#token=ccs_public-token&tab=test-cases")
                .contains("### 4. Edge Cases and Negative Testing", "Test an expired gift card")
                .contains("### 5. Regression Risks", "Verify saved cards")
                .contains("### 6. Налаштування середовища\n\n"
                        + "https://codecrow.cloud/share#token=ccs_public-token&tab=environment")
                .contains("Generated by [CodeCrow]", "<!-- codecrow-qa-autodoc:prs=17 -->")
                .doesNotContain(
                        "Оплатити подарунковою карткою",
                        "Баланс застосовано",
                        "Use the QA payment environment",
                        "codecrow-test-cases:",
                        "codecrow-environment:");
    }

    @Test
    void parseStripsGeneratedFooterButLeavesMiddleSectionsUntouched() {
        QaDocContent parsed = QaDocContentParser.parse("""
                ### 1. Summary
                Summary.

                <!-- codecrow-test-cases:start -->
                ### 3. Tests
                <!-- codecrow-test-cases:content -->
                **Works** (HIGH)
                - **Expected Result:** It works.
                <!-- codecrow-test-cases:end -->

                ### 4. Edge Cases
                Edge content.

                ### 5. Regression Risks
                Regression content.

                <!-- codecrow-environment:start -->
                ### 6. Setup
                <!-- codecrow-environment:content -->
                No special setup is required.
                <!-- codecrow-environment:end -->

                ---
                *🐦 Generated by [CodeCrow](https://codecrow.app) QA Auto-Documentation*
                <!-- codecrow-qa-autodoc:prs=17 -->
                """);

        assertThat(parsed.overviewMarkdown())
                .contains("Summary", "Edge Cases", "Edge content", "Regression Risks", "Regression content")
                .doesNotContain("Generated by", "codecrow-qa-autodoc", "### 3. Tests", "### 6. Setup");
        assertThat(parsed.environmentMarkdown()).isEqualTo("No special setup is required.");
    }

    @Test
    void rejectsJiraReplacementWhenEitherSentinelBlockIsIncomplete() {
        String missingEnvironmentBlock = """
                <!-- codecrow-test-cases:start -->
                ### 3. Tests
                <!-- codecrow-test-cases:content -->
                **Works** (HIGH)
                - **Expected Result:** It works.
                <!-- codecrow-test-cases:end -->

                ### 6. Environment and Setup Notes
                Private environment content must never be posted.
                """;

        assertThatThrownBy(() -> QaDocContentParser.replaceShareableSections(
                missingEnvironmentBlock,
                "test-link",
                "environment-link"))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("environment/setup");
    }

    @Test
    void rejectsDuplicateSentinelsInsteadOfGuessingWhichBlockToUse() {
        String duplicatedTestStart = """
                <!-- codecrow-test-cases:start -->
                <!-- codecrow-test-cases:start -->
                ### 3. Tests
                <!-- codecrow-test-cases:content -->
                **Works** (HIGH)
                - **Expected Result:** It works.
                <!-- codecrow-test-cases:end -->

                <!-- codecrow-environment:start -->
                ### 6. Setup
                <!-- codecrow-environment:content -->
                No special setup.
                <!-- codecrow-environment:end -->
                """;

        assertThat(QaDocContentParser.hasCompleteShareableSections(duplicatedTestStart)).isFalse();
        assertThat(QaDocContentParser.parseMarkedTestCases(duplicatedTestStart)).isEmpty();
    }

    @Test
    void rejectsBodyTextPlacedInTheHeadingSlot() {
        String invalid = """
                <!-- codecrow-test-cases:start -->
                ### 3. Tests
                This must not leak into Jira before the link.
                <!-- codecrow-test-cases:content -->
                **Works** (HIGH)
                <!-- codecrow-test-cases:end -->

                <!-- codecrow-environment:start -->
                ### 6. Setup
                <!-- codecrow-environment:content -->
                No special setup.
                <!-- codecrow-environment:end -->
                """;

        assertThat(QaDocContentParser.hasCompleteShareableSections(invalid)).isFalse();
        assertThatThrownBy(() -> QaDocContentParser.replaceShareableSections(
                invalid,
                "test-link",
                "environment-link"))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("test-case");
    }

    @Test
    void recognizesACompleteShareableDocumentOnlyWhenBothBlocksAreValid() {
        String complete = """
                <!-- codecrow-test-cases:start -->
                ### 3. Tests
                <!-- codecrow-test-cases:content -->
                **Works** (HIGH)
                - **Expected Result:** It works.
                <!-- codecrow-test-cases:end -->

                <!-- codecrow-environment:start -->
                ### 6. Setup
                <!-- codecrow-environment:content -->
                No special setup.
                <!-- codecrow-environment:end -->
                """;

        assertThat(QaDocContentParser.hasCompleteShareableSections(complete)).isTrue();
    }
}
